//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotAllocation
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ParkingSlotId { get; set; }
        public System.DateTime AllocationDate { get; set; }
        public int Status { get; set; }
        public string Comment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ParkingSlot ParkingSlot { get; set; }
    }
}
